# plz replace right token
POST http://localhost:8179/api/example/hello
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzb3VyY2Utc2VydmVyIl0sInVzZXJfbmFtZSI6InRlc3RVc2VyIiwic2NvcGUiOlsicmVhZF91c2VyaW5mbyJdLCJleHAiOjE2MjIzODk2NjcsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiJkNjMyOWZhNS0xMDQxLTQ4N2UtODQwMi00ZGIxNzk0ODU5YjUiLCJjbGllbnRfaWQiOiJzaGVueXUifQ.k1MC118p2O0Bn9RPqcjDdIyBSGsHHnUR8-IAnYDq8Vs

###